# Generated by Django 4.1 on 2023-11-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ubicacion", models.CharField(max_length=100)),
                ("Empleados", models.IntegerField()),
                ("CelularContacto", models.CharField(max_length=100)),
                ("CorreoContacto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Producto", models.CharField(max_length=100)),
                ("Descripcion", models.CharField(max_length=100)),
                ("Cantidad", models.IntegerField()),
                ("FechaDeStock", models.DateField()),
                (
                    "tienda_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="informeAPI.tienda",
                    ),
                ),
            ],
        ),
    ]
