# Generated by Django 4.1 on 2023-11-28 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("informeAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="FechaDeStock",
        ),
    ]
