# Generated by Django 4.1 on 2023-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informeAPI", "0004_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=250)),
                ("correo", models.CharField(max_length=250)),
                ("contraseña", models.CharField(max_length=250)),
            ],
        ),
    ]
