# Generated by Django 4.1 on 2023-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informeAPI", "0005_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="Precio",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
